require('base_settings')
require('plugins')
require('commands')
require('maps')
vim.cmd("source ~/.config/nvim/commands.vim")
pcall(require, 'user/user_settings')
pcall(require, 'user/user_commands')
pcall(require, 'user/user_maps')
local config = require('user.get_config')
vim.cmd("colorscheme " .. config.colorscheme)
